#!/usr/bin/env python
"""Extract thesis Word drafts into Markdown chapter files.

This tool is conservative: it preserves source wording, inline citation markers,
reference paragraphs, and simple tables. It does not improve prose. Editing and
scientific review happen after extraction in the Markdown files.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
NS = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}

DEFAULT_MAP = {
    "source_documents/word_drafts/Ch0 - Thesis outline.docx": "chapters/ch00_detailed_thesis_outline.md",
    "source_documents/word_drafts/Thesis Outline.docx": "chapters/thesis_outline.md",
    "source_documents/word_drafts/Ch1 - Introduction.docx": "chapters/ch01_introduction.md",
    "source_documents/word_drafts/Ch3 - Methodology.docx": "chapters/ch03_methodology.md",
    "source_documents/word_drafts/Chapter 4 - Study1.docx": "chapters/ch04_study1_reflective_coating.md",
    "source_documents/thesis_summaries/Thesis Summary.docx": "chapters/thesis_summary.md",
}

TITLE_BY_TARGET = {
    "chapters/ch00_detailed_thesis_outline.md": "Detailed Thesis Outline",
    "chapters/thesis_outline.md": "Thesis Outline",
    "chapters/ch01_introduction.md": "Chapter 1: Introduction",
    "chapters/ch03_methodology.md": "Chapter 3: Methodology",
    "chapters/ch04_study1_reflective_coating.md": "Chapter 4: Development of an Enhanced Coating for a Scintillation Detector",
    "chapters/thesis_summary.md": "Thesis Summary",
}


def normalize_text(value: str) -> str:
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u2011": "-",
        "\u00a0": " ",
        "\u00b5": "u",
        "\u00d7": "x",
    }
    for old, new in replacements.items():
        value = value.replace(old, new)
    return re.sub(r"[ \t]+", " ", value).strip()


def text_from_element(element: ET.Element) -> str:
    return normalize_text("".join(t.text or "" for t in element.findall(".//w:t", NS)))


def paragraph_style(paragraph: ET.Element) -> str:
    ppr = paragraph.find("w:pPr", NS)
    if ppr is None:
        return ""
    style = ppr.find("w:pStyle", NS)
    if style is None:
        return ""
    return style.attrib.get(f"{{{NS['w']}}}val", "")


def heading_level(style: str, text: str) -> int:
    lowered = style.lower()
    if "heading1" in lowered or re.match(r"^chapter\s+\d+", text, re.I):
        return 1
    if "heading2" in lowered:
        return 2
    if "heading3" in lowered:
        return 3

    known_h2 = {
        "Research Background",
        "Research Gap",
        "Objectives of the study",
        "Research Questions",
        "Research Scope and Limitations",
        "Introduction",
        "Materials and Methods",
        "Results and Discussion",
        "References",
        "REFERENCES",
    }
    if text in known_h2:
        return 2
    if re.match(r"^\d+\.\d+", text):
        return 3
    return 0


def iter_blocks(document_xml: bytes):
    root = ET.fromstring(document_xml)
    body = root.find("w:body", NS)
    if body is None:
        return
    for child in body:
        tag = child.tag.split("}", 1)[-1]
        if tag == "p":
            text = text_from_element(child)
            if text:
                yield ("paragraph", paragraph_style(child), text)
        elif tag == "tbl":
            rows = []
            for row in child.findall(".//w:tr", NS):
                cells = [text_from_element(cell) for cell in row.findall("w:tc", NS)]
                if any(cells):
                    rows.append(cells)
            if rows:
                yield ("table", "", rows)


def docx_to_markdown(source: Path, target_rel: str) -> str:
    today = dt.date.today().isoformat()
    title = TITLE_BY_TARGET.get(target_rel, source.stem)
    rel_source = source.relative_to(ROOT).as_posix()

    lines = [
        "---",
        f'title: "{title}"',
        'status: "source-derived draft"',
        f'source: "{rel_source}"',
        f'last_extracted: "{today}"',
        "---",
        "",
        "<!--",
        "Generated by tools/extract_docx_to_md.py.",
        "Preserve this file as the editable layer. Improve prose here after extraction.",
        "-->",
        "",
    ]

    with zipfile.ZipFile(source) as archive:
        document_xml = archive.read("word/document.xml")

    previous_heading = ""
    for kind, style, value in iter_blocks(document_xml):
        if kind == "table":
            lines.extend(markdown_table(value))
            previous_heading = ""
            continue

        text = value
        level = heading_level(style, text)
        if level:
            heading = f"{'#' * level} {text}"
            if heading != previous_heading:
                lines.extend([heading, ""])
                previous_heading = heading
        else:
            lines.extend([text, ""])
            previous_heading = ""

    return "\n".join(lines).rstrip() + "\n"


def markdown_table(rows: list[list[str]]) -> list[str]:
    width = max(len(row) for row in rows)
    padded = [row + [""] * (width - len(row)) for row in rows]
    header = padded[0]
    lines = []
    lines.append("| " + " | ".join(escape_table_cell(cell) for cell in header) + " |")
    lines.append("| " + " | ".join("---" for _ in header) + " |")
    for row in padded[1:]:
        lines.append("| " + " | ".join(escape_table_cell(cell) for cell in row) + " |")
    lines.append("")
    return lines


def escape_table_cell(value: str) -> str:
    return value.replace("|", "\\|")


def extract_one(source: Path, target: Path, force: bool) -> None:
    if not source.exists():
        raise FileNotFoundError(source)
    if target.exists() and not force:
        raise FileExistsError(f"{target} already exists. Use --force to overwrite.")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(docx_to_markdown(source, target.relative_to(ROOT).as_posix()), encoding="utf-8", newline="\n")
    print(f"extracted {source.relative_to(ROOT)} -> {target.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Extract thesis DOCX drafts to Markdown.")
    parser.add_argument("--all", action="store_true", help="Extract all mapped source DOCX files.")
    parser.add_argument("--source", help="Source DOCX path, relative to workspace or absolute.")
    parser.add_argument("--out", help="Output Markdown path, relative to workspace or absolute.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing Markdown output.")
    args = parser.parse_args()

    if args.all:
        for source_rel, target_rel in DEFAULT_MAP.items():
            extract_one(ROOT / source_rel, ROOT / target_rel, force=True)
        return 0

    if not args.source or not args.out:
        parser.error("Use --all or provide both --source and --out.")

    source = Path(args.source)
    target = Path(args.out)
    if not source.is_absolute():
        source = ROOT / source
    if not target.is_absolute():
        target = ROOT / target
    extract_one(source, target, args.force)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

